# MySQL datasource - ajusta usuario/clave/host según tu entorno
spring.application.name=backpasteleria

spring.datasource.url=jdbc:mysql://localhost:3306/pasteleria_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Permitir acceso libre a Swagger y a la API
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT settings
jwt.secret=changeit-changeit-changeit-0123456789
jwt.expiration-ms=3600000

# Puerto del servidor (por defecto 8080)
server.port=8080
